kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "chart.fullname" . }}-pv-volume
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistentVolume.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
